-- 投融资对接平台数据库建表脚本
-- 基于实体类生成

-- 创建数据库（如果不存在）
CREATE DATABASE IF NOT EXISTS investment DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE investment;

-- 1. 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    phone VARCHAR(20) NOT NULL UNIQUE COMMENT '手机号',
    password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
    email VARCHAR(100) COMMENT '邮箱',
    user_type VARCHAR(20) NOT NULL COMMENT '用户类型: INVESTOR/ENTREPRENEUR',
    real_name VARCHAR(50) COMMENT '真实姓名',
    avatar_url VARCHAR(500) COMMENT '头像URL',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING/ACTIVE/INACTIVE/BANNED',
    is_verified BOOLEAN DEFAULT FALSE COMMENT '是否实名认证',
    last_login_at DATETIME COMMENT '最后登录时间',
    last_viewed_project_id BIGINT COMMENT '最后查看的项目ID',
    last_viewed_teaser_id BIGINT COMMENT '最后查看的Teaser ID',
    notification_count INT DEFAULT 0 COMMENT '未读通知数量',
    unread_question_count INT DEFAULT 0 COMMENT '未读问题数量',
    profile_completion_rate INT DEFAULT 0 COMMENT '资料完善度百分比',
    preferences JSON COMMENT '用户偏好设置',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME COMMENT '软删除时间',
    INDEX idx_phone (phone),
    INDEX idx_email (email),
    INDEX idx_user_type (user_type),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- 2. 投资人资料表
CREATE TABLE IF NOT EXISTS investor_profiles (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL UNIQUE COMMENT '用户ID',
    avatar_url VARCHAR(500) COMMENT '头像URL',
    institution_name VARCHAR(200) COMMENT '机构名称',
    position VARCHAR(100) COMMENT '职位',
    department VARCHAR(100) COMMENT '部门',
    work_years INT COMMENT '从业年限',
    institution_type VARCHAR(50) COMMENT '机构类型',
    investment_stage VARCHAR(255) COMMENT '投资阶段偏好',
    investment_industries VARCHAR(255) COMMENT '投资行业偏好',
    investment_region VARCHAR(255) COMMENT '投资地区偏好',
    investment_range_min DECIMAL(12,2) COMMENT '最小投资金额(万)',
    investment_range_max DECIMAL(12,2) COMMENT '最大投资金额(万)',
    phone VARCHAR(20) COMMENT '联系电话',
    wechat VARCHAR(100) COMMENT '微信号',
    introduction TEXT COMMENT '个人/机构简介',
    investment_philosophy TEXT COMMENT '投资理念',
    notable_investments TEXT COMMENT '知名投资案例',
    website_url VARCHAR(500) COMMENT '官网URL',
    linkedin_url VARCHAR(500) COMMENT '领英链接',
    investment_score INT DEFAULT 50 COMMENT '投资评分(0-100)',
    activity_level VARCHAR(20) DEFAULT 'medium' COMMENT '活跃度',
    response_rate DECIMAL(5,2) COMMENT '回复率(%)',
    avg_response_time INT COMMENT '平均回复时间(小时)',
    investment_count INT DEFAULT 0 COMMENT '投资项目数',
    followers_count INT DEFAULT 0 COMMENT '关注者数量',
    is_verified BOOLEAN DEFAULT FALSE COMMENT '是否已认证',
    verification_level VARCHAR(20) DEFAULT 'basic' COMMENT '认证等级',
    preferences JSON COMMENT '投资偏好设置',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_user_id (user_id),
    INDEX idx_institution_name (institution_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投资人资料表';

-- 3. 融资用户资料表
CREATE TABLE IF NOT EXISTS entrepreneur_profiles (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL UNIQUE COMMENT '用户ID',
    company_name VARCHAR(200) NOT NULL COMMENT '公司名称',
    company_logo_url VARCHAR(500) COMMENT '公司logo URL',
    industry VARCHAR(50) COMMENT '所属行业',
    business_license_number VARCHAR(100) COMMENT '营业执照号',
    legal_representative VARCHAR(100) COMMENT '法定代表人',
    registered_capital DECIMAL(15,2) COMMENT '注册资本(万)',
    location VARCHAR(100) COMMENT '公司所在地',
    office_address VARCHAR(500) COMMENT '办公地址',
    company_stage VARCHAR(20) COMMENT '公司阶段',
    founded_date DATE COMMENT '成立时间',
    team_size INT COMMENT '团队规模',
    contact_person VARCHAR(100) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    contact_email VARCHAR(100) COMMENT '联系邮箱',
    business_hours VARCHAR(100) COMMENT '营业时间',
    website_url VARCHAR(500) COMMENT '官网URL',
    social_media_urls JSON COMMENT '社交媒体链接',
    introduction TEXT COMMENT '公司简介',
    product_description TEXT COMMENT '产品/服务描述',
    target_customers TEXT COMMENT '目标客户群体',
    core_advantages TEXT COMMENT '核心优势',
    development_plans TEXT COMMENT '发展规划',
    profile_completion_rate INT DEFAULT 0 COMMENT '资料完善度',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_user_id (user_id),
    INDEX idx_company_name (company_name),
    INDEX idx_industry (industry)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='融资用户资料表';

-- 4. 项目表
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    entrepreneur_user_id BIGINT NOT NULL COMMENT '融资用户ID',
    project_name VARCHAR(200) NOT NULL COMMENT '项目名称',
    project_code VARCHAR(50) UNIQUE COMMENT '项目编码',
    industry VARCHAR(50) COMMENT '所属行业',
    location VARCHAR(100) COMMENT '项目所在地',
    company_founded_date DATE COMMENT '公司成立日期',
    office_address VARCHAR(500) COMMENT '办公地址',
    company_website VARCHAR(255) COMMENT '公司官网',
    financing_stage VARCHAR(20) COMMENT '融资阶段',
    financing_amount DECIMAL(12,2) COMMENT '融资金额(万)',
    valuation DECIMAL(15,2) COMMENT '估值(万)',
    equity_percentage DECIMAL(5,2) COMMENT '出让股权比例(%)',
    financing_history TEXT COMMENT '融资历史',
    one_line_description VARCHAR(500) COMMENT '一句话描述',
    business_description TEXT COMMENT '业务描述',
    logo_url VARCHAR(500) COMMENT '公司logo URL',
    business_plan_file_url VARCHAR(500) COMMENT '商业计划书文件URL',
    market_size TEXT COMMENT '市场规模',
    competitive_advantage TEXT COMMENT '竞争优势',
    contact_person VARCHAR(100) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    contact_email VARCHAR(100) COMMENT '联系邮箱',
    business_model TEXT COMMENT '商业模式',
    revenue_ytd DECIMAL(12,2) COMMENT '当年营收(万)',
    revenue_last_year DECIMAL(12,2) COMMENT '去年营收(万)',
    gross_margin DECIMAL(5,2) COMMENT '毛利率(%)',
    team_size INT COMMENT '团队规模',
    status VARCHAR(20) DEFAULT 'DRAFT' COMMENT '状态: DRAFT/SUBMITTED/ACTIVE/FINANCED/ARCHIVED',
    is_anonymous BOOLEAN DEFAULT TRUE COMMENT '是否匿名显示',
    view_count INT DEFAULT 0 COMMENT '浏览次数',
    favorite_count INT DEFAULT 0 COMMENT '收藏次数',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (entrepreneur_user_id) REFERENCES users(id),
    INDEX idx_entrepreneur_user_id (entrepreneur_user_id),
    INDEX idx_project_code (project_code),
    INDEX idx_industry (industry),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目表';

-- 5. 商业计划书表
CREATE TABLE IF NOT EXISTS business_plans (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL COMMENT '项目ID',
    file_name VARCHAR(255) NOT NULL COMMENT '文件名',
    file_url VARCHAR(500) NOT NULL COMMENT '文件URL',
    thumbnail_url VARCHAR(500) COMMENT '缩略图URL',
    file_size INT COMMENT '文件大小(字节)',
    page_count INT COMMENT '页数',
    file_format VARCHAR(10) COMMENT '文件格式',
    file_hash VARCHAR(64) COMMENT '文件哈希值',
    upload_status VARCHAR(20) DEFAULT 'UPLOADING' COMMENT '上传状态: UPLOADING/COMPLETED/FAILED',
    upload_source VARCHAR(20) DEFAULT 'web' COMMENT '上传来源',
    teaser_generation_status VARCHAR(20) DEFAULT 'PENDING' COMMENT 'Teaser生成状态',
    extraction_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '内容提取状态',
    extracted_content JSON COMMENT '提取的内容',
    ai_analysis_status VARCHAR(20) DEFAULT 'PENDING' COMMENT 'AI分析状态',
    analysis_id BIGINT COMMENT '关联的分析记录ID',
    teaser_id BIGINT COMMENT '关联的Teaser ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (project_id) REFERENCES projects(id),
    INDEX idx_project_id (project_id),
    INDEX idx_upload_status (upload_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商业计划书表';

-- 6. Teaser表
CREATE TABLE IF NOT EXISTS teasers (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL COMMENT '项目ID',
    business_plan_id BIGINT COMMENT '商业计划书ID',
    title VARCHAR(200) NOT NULL COMMENT '标题',
    cover_image_url VARCHAR(500) COMMENT '封面图片URL',
    subtitle VARCHAR(500) COMMENT '副标题',
    company_name VARCHAR(200) COMMENT '公司名称',
    is_anonymous_company BOOLEAN DEFAULT TRUE COMMENT '是否匿名显示公司名称',
    icon_emoji VARCHAR(10) COMMENT '图标emoji',
    ai_summary TEXT COMMENT 'AI生成的项目摘要',
    key_metrics JSON COMMENT '关键指标数据',
    company_overview TEXT COMMENT '公司概述',
    core_business TEXT COMMENT '核心业务',
    team_description TEXT COMMENT '团队简介',
    product_description TEXT COMMENT '产品描述',
    customer_cases TEXT COMMENT '客户案例',
    investment_highlights TEXT COMMENT '投资亮点',
    risk_factors TEXT COMMENT '风险因素',
    contact_permission_required BOOLEAN DEFAULT TRUE COMMENT '是否需要申请才能查看联系方式',
    market_size TEXT COMMENT '市场规模',
    competitive_advantage TEXT COMMENT '竞争优势',
    financial_data JSON COMMENT '财务数据',
    financing_plan TEXT COMMENT '融资计划',
    tags VARCHAR(255) COMMENT '标签',
    view_count INT DEFAULT 0 COMMENT '浏览次数',
    favorite_count INT DEFAULT 0 COMMENT '收藏次数',
    match_score_avg DECIMAL(5,2) DEFAULT 0 COMMENT '平均匹配度',
    status VARCHAR(20) DEFAULT 'DRAFT' COMMENT '状态: DRAFT/PENDING/PUBLISHED/HIDDEN/EXPIRED',
    ai_analysis_ready BOOLEAN DEFAULT FALSE COMMENT 'AI分析是否已生成',
    last_analyzed_at DATETIME COMMENT '最后AI分析时间',
    sharing_url VARCHAR(255) COMMENT '分享链接',
    expire_date DATE COMMENT 'Teaser过期日期',
    generated_at DATETIME COMMENT '生成时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (business_plan_id) REFERENCES business_plans(id),
    INDEX idx_project_id (project_id),
    INDEX idx_status (status),
    INDEX idx_expire_date (expire_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Teaser表';

-- 7. 申请表
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    application_type VARCHAR(20) NOT NULL COMMENT '申请类型: BP_ACCESS/CONTACT_ACCESS',
    investor_user_id BIGINT NOT NULL COMMENT '投资人用户ID',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    entrepreneur_user_id BIGINT NOT NULL COMMENT '融资用户ID',
    teaser_id BIGINT COMMENT 'Teaser ID',
    bp_id BIGINT COMMENT 'BP ID',
    contact_info VARCHAR(500) COMMENT '联系信息',
    application_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '申请状态: PENDING/APPROVED/REJECTED/EXPIRED',
    application_reason TEXT COMMENT '申请理由',
    rejection_reason TEXT COMMENT '拒绝原因',
    admin_notes TEXT COMMENT '管理员备注',
    reviewed_by BIGINT COMMENT '审核人ID',
    reviewed_at DATETIME COMMENT '审核时间',
    expires_at DATETIME COMMENT '申请过期时间',
    viewed_count INT DEFAULT 0 COMMENT '查看次数',
    last_viewed_at DATETIME COMMENT '最后查看时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (investor_user_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (entrepreneur_user_id) REFERENCES users(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id),
    INDEX idx_investor_user_id (investor_user_id),
    INDEX idx_project_id (project_id),
    INDEX idx_entrepreneur_user_id (entrepreneur_user_id),
    INDEX idx_application_status (application_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='申请表';

-- 8. 问答记录表
CREATE TABLE IF NOT EXISTS qa_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL COMMENT '项目ID',
    investor_user_id BIGINT NOT NULL COMMENT '投资人用户ID',
    entrepreneur_user_id BIGINT NOT NULL COMMENT '融资用户ID',
    question TEXT NOT NULL COMMENT '问题内容',
    investor_message TEXT COMMENT '投资人留言',
    answer TEXT COMMENT '回答内容',
    draft_answer TEXT COMMENT '草稿回答内容',
    is_public BOOLEAN DEFAULT FALSE COMMENT '是否公开',
    is_from_question_library BOOLEAN DEFAULT FALSE COMMENT '是否来自问题库',
    question_library_id BIGINT COMMENT '问题库问题ID',
    allow_public BOOLEAN DEFAULT TRUE COMMENT '融资方是否允许公开此问答',
    use_privacy_setting BOOLEAN DEFAULT TRUE COMMENT '是否使用隐私设置',
    question_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '问题状态: PENDING/ANSWERED/CLOSED',
    sent_at DATETIME COMMENT '发送时间',
    answered_at DATETIME COMMENT '回答时间',
    investor_viewed_at DATETIME COMMENT '投资人查看回复的时间',
    entrepreneur_viewed_at DATETIME COMMENT '融资方查看问题的时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (investor_user_id) REFERENCES users(id),
    FOREIGN KEY (entrepreneur_user_id) REFERENCES users(id),
    INDEX idx_project_id (project_id),
    INDEX idx_investor_user_id (investor_user_id),
    INDEX idx_entrepreneur_user_id (entrepreneur_user_id),
    INDEX idx_question_status (question_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问答记录表';

-- 9. 实名认证表
CREATE TABLE IF NOT EXISTS user_verifications (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    verification_type VARCHAR(20) NOT NULL COMMENT '认证类型',
    real_name VARCHAR(50) NOT NULL COMMENT '真实姓名',
    id_card_number VARCHAR(18) COMMENT '身份证号',
    id_card_front_url VARCHAR(500) COMMENT '身份证正面照片URL',
    id_card_back_url VARCHAR(500) COMMENT '身份证背面照片URL',
    business_license_url VARCHAR(500) COMMENT '营业执照URL',
    business_card_url VARCHAR(500) COMMENT '名片URL',
    additional_documents JSON COMMENT '其他证明材料',
    company_name VARCHAR(200) COMMENT '公司名称',
    position VARCHAR(100) COMMENT '职位',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    contact_email VARCHAR(100) COMMENT '联系邮箱',
    verification_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '审核状态: PENDING/APPROVED/REJECTED',
    reject_reason TEXT COMMENT '拒绝原因',
    admin_notes TEXT COMMENT '管理员备注',
    reviewed_by BIGINT COMMENT '审核人ID',
    reviewed_at DATETIME COMMENT '审核时间',
    verified_until DATE COMMENT '认证有效期',
    submission_source VARCHAR(20) DEFAULT 'web' COMMENT '提交来源',
    ip_address VARCHAR(45) COMMENT '提交IP地址',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_user_id (user_id),
    INDEX idx_verification_status (verification_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实名认证表';

-- 10. 通知表
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '接收用户ID',
    notification_type VARCHAR(50) NOT NULL COMMENT '通知类型',
    title VARCHAR(255) NOT NULL COMMENT '通知标题',
    content TEXT COMMENT '通知内容',
    related_id BIGINT COMMENT '关联ID',
    related_type VARCHAR(50) COMMENT '关联类型',
    is_read BOOLEAN DEFAULT FALSE COMMENT '是否已读',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_user_id (user_id),
    INDEX idx_is_read (is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知表';

-- 11. 隐私设置表
CREATE TABLE IF NOT EXISTS privacy_settings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL UNIQUE COMMENT '用户ID',
    allow_show_company_name BOOLEAN DEFAULT FALSE COMMENT '是否允许显示公司名称',
    allow_show_founded_time BOOLEAN DEFAULT TRUE COMMENT '是否允许显示成立时间',
    allow_show_company_scale BOOLEAN DEFAULT TRUE COMMENT '是否允许显示公司规模',
    allow_show_office_address BOOLEAN DEFAULT FALSE COMMENT '是否允许显示办公地址',
    allow_show_contact_info BOOLEAN DEFAULT FALSE COMMENT '是否允许显示联系方式',
    allow_show_financial_data BOOLEAN DEFAULT FALSE COMMENT '是否允许显示详细财务数据',
    allow_show_financing_history BOOLEAN DEFAULT TRUE COMMENT '是否允许显示融资历史',
    allow_show_founder_details BOOLEAN DEFAULT FALSE COMMENT '是否允许显示创始人详细信息',
    allow_show_team_info BOOLEAN DEFAULT TRUE COMMENT '是否允许显示核心团队信息',
    allow_public_qa BOOLEAN DEFAULT TRUE COMMENT '是否允许公开问答',
    default_qa_public BOOLEAN DEFAULT TRUE COMMENT '新回复默认是否公开',
    question_library_qa_public BOOLEAN DEFAULT TRUE COMMENT '问题库回复默认是否公开',
    require_bp_approval BOOLEAN DEFAULT TRUE COMMENT '是否需要审核才能查看完整BP',
    require_contact_approval BOOLEAN DEFAULT TRUE COMMENT '是否需要审核才能获取联系方式',
    allow_view_qa_records BOOLEAN DEFAULT TRUE COMMENT '是否允许投资人查看问答记录',
    allow_receive_questions BOOLEAN DEFAULT TRUE COMMENT '是否允许接收投资人提问',
    auto_reply_template TEXT COMMENT '自动回复模板',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='隐私设置表';

-- 12. 收藏表（投资人收藏Teaser）
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    teaser_id BIGINT NOT NULL COMMENT 'Teaser ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (teaser_id) REFERENCES teasers(id),
    UNIQUE KEY uk_user_teaser (user_id, teaser_id),
    INDEX idx_user_id (user_id),
    INDEX idx_teaser_id (teaser_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收藏表';

-- 13. 投资分析表
CREATE TABLE IF NOT EXISTS investment_analyses (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    teaser_id BIGINT NOT NULL COMMENT 'Teaser ID',
    investor_user_id BIGINT NOT NULL COMMENT '投资人用户ID',
    analysis_type VARCHAR(50) COMMENT '分析类型',
    analysis_content JSON COMMENT '分析内容',
    score DECIMAL(5,2) COMMENT '评分',
    recommendation VARCHAR(100) COMMENT '推荐意见',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY (teaser_id) REFERENCES teasers(id),
    FOREIGN KEY (investor_user_id) REFERENCES users(id),
    INDEX idx_teaser_id (teaser_id),
    INDEX idx_investor_user_id (investor_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投资分析表';

-- 14. 浏览记录表
CREATE TABLE IF NOT EXISTS view_histories (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL COMMENT '用户ID',
    teaser_id BIGINT COMMENT 'Teaser ID',
    project_id BIGINT COMMENT '项目ID',
    view_duration INT COMMENT '浏览时长(秒)',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (teaser_id) REFERENCES teasers(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    INDEX idx_user_id (user_id),
    INDEX idx_teaser_id (teaser_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='浏览记录表';

-- 15. 投资人问题库表
CREATE TABLE IF NOT EXISTS investor_questions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT COMMENT '创建用户ID',
    question TEXT NOT NULL COMMENT '问题内容',
    category VARCHAR(50) COMMENT '问题分类',
    is_template BOOLEAN DEFAULT FALSE COMMENT '是否为模板问题',
    use_count INT DEFAULT 0 COMMENT '使用次数',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    INDEX idx_category (category),
    INDEX idx_is_template (is_template)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投资人问题库表';
